"""refactor_profiles

Revision ID: 6b00c4e95d35
Revises: adca7dcc37e8
Create Date: 2021-07-21 17:16:00.398476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b00c4e95d35'
down_revision = 'adca7dcc37e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('information', sa.Text(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'information')
    op.drop_column('profiles', 'name')
    # ### end Alembic commands ###
